default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: postgres
  pool: 5
  timeout: 5000
  host: localhost
development:
  <<: *default
  database: hopee_shopping_cart_development
test:
  <<: *default
  database: hopee_shopping_cart_test
production:
  <<: *default
  database: hopee_shopping_cart_production
